<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CJ2LCU7" failures="1" tests="1" name="Test" time="2.131" errors="0" timestamp="2024-02-28T15:03:47 IST">
  <testcase classname="com.Collabera.datadriven.Logintest" name="Logincasetest" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at com.Collabera.datadriven.DataDrivenTesting.fetchExcelData(DataDrivenTesting.java:26)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Logincasetest -->
</testsuite> <!-- Test -->
